import type { Metadata } from "next";

/**
 * Per-page SEO metadata: canonical URL, Open Graph and Twitter card.
 *
 * Paths are site-relative ("/blogs/my-post"); Next.js resolves them against
 * metadataBase (NEXT_PUBLIC_SITE_URL, set in the root layout), so the
 * canonical and og:url are absolute and never include query strings.
 */

export const SITE_NAME = "GlobalEd";
export const DEFAULT_TITLE = "GlobalEd | IELTS & Study Abroad Consultancy";

/** 1200×630 PNG generated by src/app/share-image.png/route.tsx. */
export const DEFAULT_SHARE_IMAGE = {
  url: "/share-image.png",
  width: 1200,
  height: 630,
  alt: "GlobalEd — IELTS & Study Abroad Consultancy",
};

/**
 * Image for social previews. Facebook, WhatsApp, LinkedIn and X don't show
 * SVG, so SVG (and missing) images fall back to the default share card.
 */
export function shareImage(src?: string | null, alt?: string | null) {
  if (!src || /\.svg(\?|$)/i.test(src)) return DEFAULT_SHARE_IMAGE;
  return { url: src, alt: alt || DEFAULT_SHARE_IMAGE.alt };
}

/** Descriptions are cut at a word boundary around 160 characters for search/social snippets. */
function snippet(text: string, max = 160): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  return `${cut.slice(0, cut.lastIndexOf(" ") > 80 ? cut.lastIndexOf(" ") : cut.length)}…`;
}

interface PageSeo {
  /** Page title; the root layout adds " | GlobalEd". Use { absolute } to opt out. */
  title: string | { absolute: string };
  description: string;
  /** Canonical path, e.g. "/courses/ielts-regular". */
  path: string;
  image?: string | null;
  imageAlt?: string | null;
  type?: "website" | "article";
  /** YYYY-MM-DD, for articles. */
  publishedTime?: string;
}

export function pageMetadata({ title, description, path, image, imageAlt, type = "website", publishedTime }: PageSeo): Metadata {
  const fullTitle = typeof title === "string" ? `${title} | ${SITE_NAME}` : title.absolute;
  const desc = snippet(description);
  const img = shareImage(image, imageAlt);
  return {
    title,
    description: desc,
    alternates: { canonical: path },
    openGraph: {
      type,
      url: path,
      siteName: SITE_NAME,
      locale: "en_BD",
      title: fullTitle,
      description: desc,
      images: [img],
      ...(type === "article" && publishedTime ? { publishedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description: desc,
      images: [{ url: img.url, alt: img.alt }],
    },
  };
}
