-- CreateEnum
CREATE TYPE "ContentStatus" AS ENUM ('DRAFT', 'PUBLISHED');

-- CreateEnum
CREATE TYPE "FaqCategory" AS ENUM ('GENERAL', 'STUDY_ABROAD', 'IELTS');

-- CreateEnum
CREATE TYPE "TeamGroup" AS ENUM ('BOARD', 'TEAM');

-- CreateTable
CREATE TABLE "Service" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "icon" TEXT NOT NULL,
    "shortDescription" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "benefits" TEXT[],
    "process" JSONB NOT NULL,
    "status" "ContentStatus" NOT NULL DEFAULT 'PUBLISHED',
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "seoTitle" TEXT NOT NULL DEFAULT '',
    "metaDescription" TEXT NOT NULL DEFAULT '',
    "ogImage" TEXT NOT NULL DEFAULT '',
    "ogImageAlt" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Faq" (
    "id" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "category" "FaqCategory" NOT NULL,
    "showOnServices" BOOLEAN NOT NULL DEFAULT false,
    "shown" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Faq_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TeamMember" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "photo" TEXT NOT NULL,
    "photoAlt" TEXT NOT NULL DEFAULT '',
    "bio" TEXT NOT NULL DEFAULT '',
    "group" "TeamGroup" NOT NULL DEFAULT 'TEAM',
    "shown" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TeamMember_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Service_slug_key" ON "Service"("slug");


-- Today's services, FAQs and team, so the site looks the same after deploy.
INSERT INTO "Service" ("id", "slug", "title", "icon", "shortDescription", "description", "benefits", "process", "status", "sortOrder", "updatedAt") VALUES ('svc_university_admission_support', 'university-admission-support', 'University Admission Support', 'GraduationCap', 'End-to-end application support — from shortlisting universities to securing your offer letter.', 'Our counsellors match your academic profile, budget, and career goals with the right universities, then manage your entire application — documents, SOP review, submission, and offer follow-up.', ARRAY['Personalized university shortlisting based on your profile', 'SOP and recommendation letter review', 'Direct liaison with 300+ partner universities', 'Application fee waivers at selected partners']::TEXT[], '[{"step":"Profile assessment","description":"We evaluate your academics, English score, and budget."},{"step":"Shortlisting","description":"You receive a tailored list of universities and courses."},{"step":"Application","description":"We prepare and submit complete, error-free applications."},{"step":"Offer letter","description":"We follow up until your conditional or unconditional offer arrives."}]'::jsonb, 'PUBLISHED', 0, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Service" ("id", "slug", "title", "icon", "shortDescription", "description", "benefits", "process", "status", "sortOrder", "updatedAt") VALUES ('svc_scholarship_guidance', 'scholarship-guidance', 'Scholarship Guidance', 'Award', 'Find and win scholarships that reduce your tuition — from merit awards to country-specific funds.', 'We track scholarship opportunities across all 13 destinations — university merit awards, government schemes like Chevening and GKS, and destination-specific funds — then help you apply with a strong case.', ARRAY['Scholarship matching based on your grades and destination', 'Application essay and interview preparation', 'Up-to-date deadline tracking', 'Partial to full-funding options identified early']::TEXT[], '[{"step":"Eligibility check","description":"We identify every scholarship you qualify for."},{"step":"Documentation","description":"We prepare transcripts, essays, and references."},{"step":"Submission","description":"Applications go out before deadlines — never last minute."},{"step":"Award follow-up","description":"We negotiate and confirm your award with the university."}]'::jsonb, 'PUBLISHED', 1, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Service" ("id", "slug", "title", "icon", "shortDescription", "description", "benefits", "process", "status", "sortOrder", "updatedAt") VALUES ('svc_documentation_guideline', 'documentation-guideline', 'Documentation Guideline', 'FileCheck', 'Get every document right the first time — transcripts, financials, SOPs, and embassy formats.', 'Most visa refusals trace back to documentation errors. Our compliance team double-checks every page of your file — academic records, bank statements, affidavits, and translations — against the exact embassy checklist.', ARRAY['Country-specific document checklists', 'Financial document and bank statement guidance', 'Translation and notarization support', 'Double cross-check before every submission']::TEXT[], '[{"step":"Checklist","description":"You receive a document list for your destination."},{"step":"Collection","description":"We help you gather and format each document."},{"step":"Verification","description":"Two senior officers review your complete file."},{"step":"Submission-ready","description":"Your file is sealed and submitted with confidence."}]'::jsonb, 'PUBLISHED', 2, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Service" ("id", "slug", "title", "icon", "shortDescription", "description", "benefits", "process", "status", "sortOrder", "updatedAt") VALUES ('svc_visa_application', 'visa-application', 'Visa Application', 'Plane', 'Step-by-step visa filing with mock interviews — the reason behind our 97% visa success rate.', 'From filling embassy forms to preparing for credibility interviews, our visa team handles the complete process. We run mock interviews, review your financial story, and file your application with precision.', ARRAY['Complete visa form filling and appointment booking', 'One-to-one mock interview sessions', 'Financial documentation strategy', '97% visa success rate across all destinations']::TEXT[], '[{"step":"Visa file preparation","description":"We assemble your complete visa file."},{"step":"Mock interview","description":"Practice sessions with real embassy-style questions."},{"step":"Submission","description":"Your application is filed and tracked."},{"step":"Decision","description":"We support you until the visa is in your passport."}]'::jsonb, 'PUBLISHED', 3, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Service" ("id", "slug", "title", "icon", "shortDescription", "description", "benefits", "process", "status", "sortOrder", "updatedAt") VALUES ('svc_pre_post_departure_guidance', 'pre-post-departure-guidance', 'Pre & Post Departure Guidance', 'Luggage', 'Briefings before you fly and support after you land — accommodation, banking, and settling in.', 'Our support doesn''t end at the visa. Before departure we brief you on travel, packing, forex, and airport procedures. After arrival we help with accommodation, local registration, banking, and staying connected.', ARRAY['Pre-departure briefing sessions with alumni', 'Accommodation and airport pickup assistance', 'Guidance on banking, SIM, and local registration', 'Ongoing student support community abroad']::TEXT[], '[{"step":"Briefing","description":"Country-specific session on what to expect."},{"step":"Travel prep","description":"Ticketing, forex, and packing guidance."},{"step":"Arrival support","description":"Airport pickup and initial settling-in help."},{"step":"Ongoing care","description":"Stay connected with our student community."}]'::jsonb, 'PUBLISHED', 4, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Service" ("id", "slug", "title", "icon", "shortDescription", "description", "benefits", "process", "status", "sortOrder", "updatedAt") VALUES ('svc_language_support', 'language-support', 'Language Support', 'Languages', 'IELTS, Spoken English, and Japanese language training under one roof.', 'Strong language scores unlock better universities and bigger scholarships. Our language wing offers IELTS preparation in three formats, Spoken English for confidence, and Japanese for students targeting Japan or language-club careers.', ARRAY['Three IELTS course formats for every schedule', 'British Council-format mock tests', 'Small batch sizes with individual feedback', 'Japanese language from certified instructors']::TEXT[], '[{"step":"Free assessment","description":"We test your current level and target band."},{"step":"Course placement","description":"You join the batch that fits your goal."},{"step":"Mock tests","description":"Regular full-format tests with band feedback."},{"step":"Test booking","description":"We book your official IELTS test when you''re ready."}]'::jsonb, 'PUBLISHED', 5, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_01', 'How to Get in Touch with GlobalEd?', 'Call our hotline at 019555 44772 or email us at info@globaled.io. You are also welcome to visit our office in person at 69/E Panthapath, Dhaka-1205 or Hossain Tower, Level-05, Sector-07, Uttara, Dhaka-1230.', 'GENERAL', false, true, 0, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_02', 'What Services Does GlobalEd Offer?', 'We provide services for study abroad, IELTS preparation and testing, language courses in English, Japanese, and Korean, skill-based training programs, as well as guidance for overseas employment opportunities.', 'GENERAL', false, true, 1, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_03', 'Where is the GlobalEd Office Located?', 'Our offices are located in Panthapath (69/E Panthapath, Dhaka-1205) and Uttara (Hossain Tower, Level-05, Sector-07, Uttara, Dhaka-1230). For detailed addresses, please visit the Contact page.', 'GENERAL', false, true, 2, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_04', 'What Are the Office Working Hours?', 'Our offices are open from 9:00 AM to 8:00 PM, Saturday through Friday.', 'GENERAL', false, true, 3, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_05', 'How Do I Discover the Perfect Program for Me?', 'It only takes a few minutes to share your academic goals and career aspirations with GlobalEd. Tell us what you want to study and where you dream of living, and we''ll match you with the best study programs tailored to your needs.', 'STUDY_ABROAD', false, true, 4, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_06', 'What''s the Application Process Like?', 'At GlobalEd, we''ve designed the application process to be smooth, transparent, and fully online. From choosing the right program to securing your visa, our expert team will guide you through every step. To begin, simply create a free account, explore your study options, and start your application at any time. With our efficient systems, you can save time and focus on preparing for your global academic journey.', 'STUDY_ABROAD', false, true, 5, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_07', 'Why Should I Choose GlobalEd?', 'Trust and guidance. GlobalEd has built a reputation for helping students turn their study abroad dreams into reality. The process of applying to universities and navigating visa requirements can feel overwhelming, but our experienced team ensures every detail is handled with care. From application to admission, we support you step-by-step — minimizing mistakes and maximizing your chances of success. With GlobalEd by your side, you can move forward with confidence.', 'STUDY_ABROAD', false, true, 6, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_08', 'Which Countries Can I Study In?', 'GlobalEd connects you with leading universities across the world''s most popular study destinations, including UK, USA, Canada, Australia, New Zealand, Sweden, Finland, Denmark, Greece, Malta, Cyprus, South Korea, and Malaysia. Through our global network, you''ll have access to diverse opportunities that match your academic and career goals.', 'STUDY_ABROAD', false, true, 7, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_09', 'What Happens After I Apply?', 'Once you submit your application, GlobalEd will coordinate with the university or college as they review your documents and make a decision. If you receive an offer, you may need to pay a tuition deposit to confirm your place. After that, our expert team will guide you through the student visa process and any additional requirements. Finally, you can celebrate and get ready to begin your study abroad journey with confidence — knowing GlobalEd is with you every step of the way.', 'STUDY_ABROAD', false, true, 8, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_10', 'Is GlobalEd''s counselling really free?', 'Yes — counselling, university shortlisting, and application support are completely free for students. We are compensated by our partner universities, never by hidden charges to you.', 'STUDY_ABROAD', false, true, 9, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_11', 'Which countries does GlobalEd cover?', 'We cover 13 destinations: UK, USA, Canada, Australia, New Zealand, Sweden, Finland, Denmark, Greece, Malta, Cyprus, South Korea, and Malaysia.', 'STUDY_ABROAD', false, true, 10, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_12', 'Can you help if I have a study gap?', 'Yes. Many of our successful students had study gaps. We build a strong, honest case around your work experience and motivation.', 'STUDY_ABROAD', false, true, 11, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_13', 'How long does the whole process take?', 'Typically 3–6 months from first counselling to visa decision, depending on your destination and intake. Starting early always helps.', 'STUDY_ABROAD', false, true, 12, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_14', 'How do I register for IELTS through GlobalEd?', 'As a British Council Authorized IELTS Registration Centre, GlobalEd handles your registration directly — simply visit our Panthapath or Uttara centre, or book a free consultation, and our team will guide you through choosing a test date, format, and package.', 'IELTS', false, true, 13, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_15', 'What''s the difference between Academic and General Training IELTS?', 'Academic IELTS is for university admission and professional registration, while General Training is typically for migration, work, and secondary education abroad. Our counsellors can help you confirm which one your target institution or country requires.', 'IELTS', false, true, 14, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_16', 'What does IELTS exam day look like at GlobalEd?', 'GlobalEd currently offers Computer-Delivered IELTS only. Listening, Reading, and Writing are completed in one sitting on the same day (around 2 hours 40 minutes with no breaks between sections); Speaking is usually scheduled the same day too, though it can occasionally be moved to within a week before or after. Bring the same valid ID used at registration — your photo is taken at the centre as an extra security check, and this is exactly the environment our Computer-Delivered mock tests are designed to mirror.', 'IELTS', false, true, 15, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_17', 'When and how will I get my results?', 'Computer-Delivered IELTS results are typically released within 1–5 days of your test date. You''ll receive an email as soon as your Test Report Form (TRF) is ready, and you can view or download it through your official IELTS candidate portal.', 'IELTS', false, true, 16, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_18', 'What is an Enquiry on Results (EOR)?', 'If you feel a section score doesn''t reflect your performance, you can apply for an EOR (remark) within 6 weeks of your test date. A senior examiner re-checks the section(s) you select, and the enquiry fee is refunded if your score improves. Outcomes can arrive the same day or take up to a few weeks.', 'IELTS', false, true, 17, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_19', 'What is One Skill Retake (OSR)?', 'OSR lets you retake just one section — Listening, Reading, Writing, or Speaking — instead of sitting the full test again, within 60 days of your original Computer-Delivered IELTS. Your new score for that section replaces the old one on a fresh TRF, while your other three scores stay locked in. If you''re also applying for an EOR on the same test, you''ll need to wait for the EOR outcome before booking your OSR.', 'IELTS', false, true, 18, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_20', 'Which package is right for me — Essential, Advanced, or Premium?', 'It depends on how much practice and mentoring support you need. Essential suits students who are already fairly confident, Advanced adds one-to-one support for steady improvement, and Premium is built for students aiming for the highest band scores with unlimited practice and priority mentoring.', 'IELTS', false, true, 19, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_21', 'Can beginners join GlobalEd, or do I need a certain level first?', 'Absolutely — our programs are designed for all proficiency levels. Starting with the Free IELTS Level Assessment helps us place you on the right track from day one.', 'IELTS', true, true, 20, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_22', 'How long does IELTS preparation usually take?', 'This varies by your current level and target band score. Your Free Level Assessment includes a recommended preparation duration, and your Progress Tracker keeps you updated as you improve.', 'IELTS', true, true, 21, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_23', 'Will someone monitor my progress throughout the course?', 'Yes. Our trainers regularly evaluate your performance, identify weaker areas, and adjust your study plan — all visible through your personal Progress Tracker.', 'IELTS', true, true, 22, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Faq" ("id", "question", "answer", "category", "showOnServices", "shown", "sortOrder", "updatedAt") VALUES ('faq_24', 'What if I need to reschedule a mock test or session?', 'Speak with your assigned trainer or our front desk as early as possible; we''ll help you find the next available slot.', 'IELTS', true, true, 23, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_board_01', 'Professor Shamim Ara Hassan', 'Chairman, Global Citizen LTD.', '/images/board/shamim-ara-hassan.webp', 'Professor Shamim Ara Hassan, Chairman, Global Citizen LTD. at GlobalEd', '', 'BOARD', true, 0, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_board_02', 'Engr. Abdul Aziz', 'Managing Director, Global Citizen LTD.', '/images/board/abdul-aziz.webp', 'Engr. Abdul Aziz, Managing Director, Global Citizen LTD. at GlobalEd', '', 'BOARD', true, 1, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_board_03', 'Engr. Abdul Alim', 'Director, Global Citizen LTD.', '/images/board/abdul-alim.webp', 'Engr. Abdul Alim, Director, Global Citizen LTD. at GlobalEd', '', 'BOARD', true, 2, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_board_04', 'Advocate Umme Salma', 'Director, Global Citizen LTD.', '/images/board/umme-salma.jpg', 'Advocate Umme Salma, Director, Global Citizen LTD. at GlobalEd', '', 'BOARD', true, 3, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_board_05', 'Ln. Mir Abdul Alim', 'Director, Global Citizen LTD.', '/images/board/mir-abdul-alim.webp', 'Ln. Mir Abdul Alim, Director, Global Citizen LTD. at GlobalEd', '', 'BOARD', true, 4, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_team_01', 'Md. Rahman', 'Founder & CEO', '/images/team/member-1.svg', 'Md. Rahman, Founder & CEO at GlobalEd', '12+ years in international education consultancy.', 'TEAM', true, 0, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_team_02', 'Sarah Ahmed', 'Head of Counselling', '/images/team/member-2.svg', 'Sarah Ahmed, Head of Counselling at GlobalEd', 'Certified counsellor for UK, Canada, and Australia admissions.', 'TEAM', true, 1, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_team_03', 'Tanvir Hasan', 'IELTS Chief Instructor', '/images/team/member-3.svg', 'Tanvir Hasan, IELTS Chief Instructor at GlobalEd', 'Band 8.5 mentor with 10 years of IELTS teaching experience.', 'TEAM', true, 2, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_team_04', 'Nusrat Jahan', 'Visa Documentation Lead', '/images/team/member-4.svg', 'Nusrat Jahan, Visa Documentation Lead at GlobalEd', 'Specialist in visa file preparation and compliance checks.', 'TEAM', true, 3, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_team_05', 'Arif Chowdhury', 'Senior Education Counsellor', '/images/team/member-5.svg', 'Arif Chowdhury, Senior Education Counsellor at GlobalEd', 'Europe destinations expert — Sweden, Finland, Denmark, and Malta.', 'TEAM', true, 4, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "TeamMember" ("id", "name", "role", "photo", "photoAlt", "bio", "group", "shown", "sortOrder", "updatedAt") VALUES ('tm_team_06', 'Priya Das', 'Student Support Manager', '/images/team/member-6.svg', 'Priya Das, Student Support Manager at GlobalEd', 'Leads pre-departure briefings and post-arrival student care.', 'TEAM', true, 5, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO NOTHING;
